apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx # Matches the label of the deployment / pods
  ports:
  # A request to a service on port 80, should target a pod running on port 8080 within that service
  - protocol: TCP
    port: 80
    targetPort: 8080 # Matches container port in pod
