apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque 
data:
  # Values base64 encoded
  mongo-root-username: dXNlcm5hbWU= # 'username'
  mongo-root-password: cGFzc3dvcmQ= # 'password'
